prc.contentType = application/json
prc.client_secret = bb1da774897f4271842F4379B7Eb44E2
prc.client_id = 99d58299e759411aac621988a467c7b9

prc.create.method = POST
prc.get.method = GET

prc.url = https://mc-lead-sys-api-kd7ppn.9675fv.sgp-s1.cloudhub.io/api/lead

api.id = 20971590

dropbox.path = "/Lead"
dropbox.consumerKey = 24aono6vqf98bzx
dropbox.consumersecret = tkpbyhvmrza44uj
dropbox.authorizationUrl = https://www.dropbox.com/oauth2/authorize
dropbox.acessTokenUrl = https://api.dropboxapi.com/oauth2/token
dropbox.callPath = /dropbox/CallBack
dropbox.authorizePath = /dropbox/authorize
dropbox.callBackUrl = https://mc-lead-prc-api-kd7ppn.9675fv.sgp-s1.cloudhub.io/dropbox/CallBack

http.port = 8081

salesforce.username = sangli.vishwa9620.e55889d2ef56@agentforce.com
salesforce.password = Sangli.Vishwa123
salesforce.securityToken = qR7Zw3N5CP8zti713qPhiexIu
salesforce.Url = https://login.salesforce.com/services/Soap/u/64.0