prc.contentType = application/json
prc.client_secret = bb1da774897f4271842F4379B7Eb44E2
prc.client_id = 99d58299e759411aac621988a467c7b9

prc.create.method = POST
prc.get.method = GET

prc.url = https://mc-lead-sys-api-kd7ppn.9675fv.sgp-s1.cloudhub.io/api/lead

api.id = 20971590